package com.sfm.model;

// Generated Jul 16, 2015 11:21:28 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fees generated by hbm2java
 */
@Entity
@Table(name = "databaseBackup", catalog = "sfm")
public class DatabaseBackup implements java.io.Serializable {

	private Integer id;	
	private Date lastBackUpDate;

	public DatabaseBackup() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public Date getLastBackUpDate() {
		return lastBackUpDate;
	}


	public void setLastBackUpDate(Date lastBackUpDate) {
		this.lastBackUpDate = lastBackUpDate;
	}

	
}
