package com.sfm.model;

// Generated Jul 16, 2015 11:21:28 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "sfm")
public class User implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String middleName;
	private String lastName;
	private String fatherName;
	private String userName;
	private String password;
	private String batch;
	private String session;
	private Date addmissionDate;
	private Boolean status;
	private String updateBy;
	private Date updatedOn;
	private Set<Fees> feeses = new HashSet<Fees>(0);
	private Set<Charges> chargeses = new HashSet<Charges>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);
	private Set<Userprofile> userprofiles = new HashSet<Userprofile>(0);

	public User() {
	}

	public User(Date addmissionDate) {
		this.addmissionDate = addmissionDate;
	}

	public User(String firstName, String middleName, String lastName,
			String fatherName,String userName, String password, String batch, String session,
			Date addmissionDate, Boolean status, String updateBy,
			Date updatedOn, Set<Fees> feeses, Set<Charges> chargeses,
			Set<Payment> payments, Set<Userprofile> userprofiles) {
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.fatherName=fatherName;
		this.userName = userName;
		this.password = password;
		this.batch = batch;
		this.session = session;
		this.addmissionDate = addmissionDate;
		this.status = status;
		this.updateBy = updateBy;
		this.updatedOn = updatedOn;
		this.feeses = feeses;
		this.chargeses = chargeses;
		this.payments = payments;
		this.userprofiles = userprofiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstName", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middleName", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "lastName", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "fatherName", length = 150)
	public String getFatherName() {
		return fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "userName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Batch", length = 25)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "session", length = 10)
	public String getSession() {
		return this.session;
	}

	public void setSession(String session) {
		this.session = session;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "addmissionDate", nullable = false, length = 19)
	public Date getAddmissionDate() {
		return this.addmissionDate;
	}

	public void setAddmissionDate(Date addmissionDate) {
		this.addmissionDate = addmissionDate;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "updateBy", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedOn", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Fees> getFeeses() {
		return this.feeses;
	}

	public void setFeeses(Set<Fees> feeses) {
		this.feeses = feeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Charges> getChargeses() {
		return this.chargeses;
	}

	public void setChargeses(Set<Charges> chargeses) {
		this.chargeses = chargeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Userprofile> getUserprofiles() {
		return this.userprofiles;
	}

	public void setUserprofiles(Set<Userprofile> userprofiles) {
		this.userprofiles = userprofiles;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", firstName=" + firstName + ", middleName="
				+ middleName + ", lastName=" + lastName + ", userName="
				+ userName + ", password=" + password + ", batch=" + batch
				+ ", session=" + session + ", addmissionDate=" + addmissionDate
				+ ", status=" + status + ", updateBy=" + updateBy
				+ ", updatedOn=" + updatedOn + ", feeses=" + feeses
				+ ", chargeses=" + chargeses + ", payments=" + payments
				+ ", userprofiles=" + userprofiles + "]";
	}

}
